Style/Documentation: # disable Missing top-level documentation comment
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb