Style/Documentation: # disable Missing top-level documentation comment
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb
Metrics/AbcSize:
  Max: 40
Metrics/MethodLength:
  Max: 20
Layout/LineLength:
  Max: 150